const mahjongData = {
    rules: [
        "莊家起手 17 隻，閒家 16 隻。",
        "必須莊家先補花叫『請』，下家才可補花，如此類推。",
        "食胡牌不可拍入原本牌內，需放開一旁。",
        "聽牌 (叮)：加 5 番，不得轉章、不得暗槓。",
        "過水限制：同巡內不可揀人食糊，需過自己摸牌後才解禁。",
        "食胡番數：計算所有牌型番數後，必須另加『底』的番數（例如底為 5，則總番數 = 牌型番 + 5）。",
        "金額比例：通常設定為『一底』的五分之一為『每一番』的錢（例如 $5 底 $1 番，16 番即 $16+$5=$21）。",
        "連莊規則：莊家續莊（連莊）時，番數會額外加成。按 (2N+1) 番計算（例如連 1 加 3 番）。",
        "拉莊機制：『拉』是指贏家胡牌後金額不即時找數，而是累積（Pending）並『繼續拉住』到下一鋪。若上一鋪贏家此鋪再胡，金額會疊加 1.5 倍，繼續累積到下一鋪；若此鋪另外 3 家其中一家自摸或上一鋪贏家出銃，金額可即時扣減一半，然後結算。"
    ],
    fanTable: [
        { category: "花、字類", fan: 1, name: "無花", condition: "沒有花牌。", example: ["🚫🌸"] },
        { category: "花、字類", fan: 2, name: "正花", condition: "花牌數字同坐位相同。", example: ["🀢 (東位1號花)"] },
        { category: "花、字類", fan: 1, name: "爛花", condition: "花牌數字同坐位不同。", example: ["🀣 (非位花)"] },
        { category: "花、字類", fan: 2, name: "正風刻子", condition: "正風牌刻子。", example: ["Ton.svg", "Ton.svg", "Ton.svg"] },
        { category: "花、字類", fan: 1, name: "非正風刻子", condition: "非正風牌刻子。", example: ["Shaa.svg", "Shaa.svg", "Shaa.svg"] },
        { category: "花、字類", fan: 2, name: "中發白刻子", condition: "中、發或白刻子。", example: ["Chun.svg", "Chun.svg", "Chun.svg"] },
        { category: "花、字類", fan: 1, name: "無字", condition: "沒有番子。", example: ["Man1.svg", "-", "Pin9.svg"] },
        { category: "花、字類", fan: 5, name: "無字花", condition: "沒有番子及沒有花。", example: ["🚫", "Ton.svg", " + 🚫🌸"] },
        { category: "花、字類", fan: 10, name: "無字花大平糊", condition: "沒有番子，沒有花，又是平胡。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Sou1.svg", "Sou2.svg", "Sou3.svg", " ", "Pin1.svg", "Pin2.svg", "Pin3.svg", " ", "Pin5.svg", "Pin6.svg", "Pin7.svg", " ", "Man1.svg", "Man1.svg"] },

        { category: "基本胡牌", fan: 5, name: "聽牌", condition: "聲明已經叫胡，不得轉章，不得暗槓，可以睇其他家的牌。", example: ["📣 聽牌！"] },
        { category: "基本胡牌", fan: 10, name: "大雞糊", condition: "不計莊前只得一番, 無其他牌型。", example: ["不計莊前只得一番, 無其他牌型"] },
        { category: "基本胡牌", fan: 1, name: "對碰", condition: "叫胡叫對碰。", example: ["Man1.svg", "Man1.svg", " ", "Ton.svg", "Ton.svg", " 等食"] },
        { category: "基本胡牌", fan: 1, name: "假獨", condition: "牌型可砌到變成食單釣或偏章。", example: ["Man1.svg", "Man1.svg", "Man2.svg", "Man3.svg", " (食", "Man1.svg", "為假獨，食", "Man4.svg", "則不是)"] },
        { category: "基本胡牌", fan: 2, name: "獨獨", condition: "單釣或叫偏章。", example: ["Man2.svg", "Man4.svg", " 食 ", "Man3.svg"] },
        { category: "基本胡牌", fan: 1, name: "將眼", condition: "以一對二、五或八做眼（筒索萬皆可）。", example: ["Man2.svg", "Man2.svg", " 或 ", "Sou5.svg", "Sou5.svg", " 或 ", "Pin8.svg", "Pin8.svg"] },
        { category: "基本胡牌", fan: 3, name: "門清", condition: "門前清，暗槓亦可。", example: ["🏠 未上碰"] },
        { category: "基本胡牌", fan: 1, name: "自摸", condition: "自己摸到胡牌。", example: ["🖐️ 自摸"] },
        { category: "基本胡牌", fan: 5, name: "門清自摸", condition: "門前清自摸。", example: ["🏠🖐️"] },
        { category: "基本胡牌", fan: 20, name: "海底撈月", condition: "最後一隻牌自摸。", example: ["🌙 尾牌"] },
        { category: "基本胡牌", fan: 3, name: "平胡", condition: "沒有刻子, 全部順子。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Sou1.svg", "Sou2.svg", "Sou3.svg", " ", "Pin1.svg", "Pin2.svg", "Pin3.svg", " ", "Pin5.svg", "Pin6.svg", "Pin7.svg", " ", "Man1.svg", "Man1.svg"] },
        { category: "基本胡牌", fan: 2, name: "老少", condition: "同門一,二,三加七,八,九 或 一,一,一加九,九,九。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " + ", "Man7.svg", "Man8.svg", "Man9.svg", " (萬子老少)"] },

        { category: "順子組合", fan: 3, name: "一般高", condition: "兩個一樣的順子。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg"] },
        { category: "順子組合", fan: 15, name: "三般高", condition: "三個一樣的順子。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg"] },
        { category: "順子組合", fan: 30, name: "四般高", condition: "四個一樣的順子。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " x 4"] },
        { category: "順子組合", fan: 2, name: "二相逢", condition: "兩款不同但數字一樣順子。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Sou1.svg", "Sou2.svg", "Sou3.svg"] },
        { category: "順子組合", fan: 10, name: "三相逢", condition: "三款不同但數字一樣順子。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Sou1.svg", "Sou2.svg", "Sou3.svg", " ", "Pin1.svg", "Pin2.svg", "Pin3.svg"] },
        { category: "順子組合", fan: 20, name: "四同順", condition: "四個數字一樣順子，不論款式，不再計三相逢/一般高/兩般高/三般高。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg", " ", "Sou1.svg", "Sou2.svg", "Sou3.svg", " ", "Pin1.svg", "Pin2.svg", "Pin3.svg"] },
        { category: "順子組合", fan: 40, name: "五同順", condition: "五個數字一樣順子，不論款式，不再計三相逢/一般高/兩般高/三般高。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg", " ", "Sou1.svg", "Sou2.svg", "Sou3.svg", " ", "Sou1.svg", "Sou2.svg", "Sou3.svg", " ", "Pin1.svg", "Pin2.svg", "Pin3.svg"] },

        { category: "刻子類", fan: 3, name: "二暗刻", condition: "手裏有兩個暗刻。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Sou1.svg", "Sou1.svg", "Sou1.svg"] },
        { category: "刻子類", fan: 10, name: "三暗刻", condition: "手裏有三個暗刻。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Sou1.svg", "Sou1.svg", "Sou1.svg", " ", "Pin1.svg", "Pin1.svg", "Pin1.svg"] },
        { category: "刻子類", fan: 30, name: "四暗刻", condition: "手裏有四個暗刻。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Sou1.svg", "Sou1.svg", "Sou1.svg", " ", "Pin1.svg", "Pin1.svg", "Pin1.svg", " ", "Ton.svg", "Ton.svg", "Ton.svg"] },
        { category: "刻子類", fan: 3, name: "二兄弟", condition: "兩款數字一樣的刻子。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Sou1.svg", "Sou1.svg", "Sou1.svg"] },
        { category: "刻子類", fan: 10, name: "小三兄弟", condition: "二兄弟加另一兄弟做眼。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Sou1.svg", "Sou1.svg", "Sou1.svg", " + ", "Pin1.svg", "Pin1.svg"] },
        { category: "刻子類", fan: 15, name: "大三兄弟", condition: "三款數字一樣的刻子。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Sou1.svg", "Sou1.svg", "Sou1.svg", " ", "Pin1.svg", "Pin1.svg", "Pin1.svg"] },
        { category: "刻子類", fan: 8, name: "小三姊妹", condition: "兩副相連刻子加一對相連眼。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Man2.svg", "Man2.svg", "Man2.svg", " + ", "Man3.svg", "Man3.svg"] },
        { category: "刻子類", fan: 15, name: "大三姊妹", condition: "三副相連刻子。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Man2.svg", "Man2.svg", "Man2.svg", " ", "Man3.svg", "Man3.svg", "Man3.svg"] },
        { category: "順子組合", fan: 5, name: "四歸一", condition: "用盡同一隻牌的四隻。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " + ", "Man1.svg", "Man2.svg", "Man3.svg"] },
        { category: "順子組合", fan: 10, name: "四歸二", condition: "用盡同一隻牌的四隻牌, 兩隻做眼。", example: ["Man1.svg", "Man1.svg", "(眼) ", "Man1.svg", "Man2.svg", "Man3.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg"] },
        { category: "順子組合", fan: 20, name: "四歸四", condition: "用盡同一隻牌的四隻牌（順子）。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg", " ", "Man2.svg", "Man3.svg", "Man4.svg", " ", "Man3.svg", "Man4.svg", "Man5.svg", " (用盡4隻", "Man3.svg", ")"] },

        { category: "龍類", fan: 10, name: "明龍", condition: "同款1-9，有上牌。", example: ["Man1.svg", "-", "Man9.svg", " (萬子龍)"] },
        { category: "龍類", fan: 20, name: "暗龍", condition: "1-9全部是是手裡的，食胡那隻可以是其他家打出。", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Man4.svg", "Man5.svg", "Man6.svg", " ", "Man7.svg", "Man8.svg", "Man9.svg", " (同款暗牌)"] },
        { category: "龍類", fan: 8, name: "明雜龍", condition: "三款湊成1-9，有上牌。", example: ["Pin1.svg", "Pin2.svg", "Pin3.svg", "(筒) ", "Man4.svg", "Man5.svg", "Man6.svg", "(萬) ", "Sou7.svg", "Sou8.svg", "Sou9.svg", "(索)"] },
        { category: "龍類", fan: 15, name: "暗雜龍", condition: "同一個款式，只有一至九，全部是手裡的。", example: ["Pin1.svg", "Pin2.svg", "Pin3.svg", "(筒) ", "Man4.svg", "Man5.svg", "Man6.svg", "(萬) ", "Sou7.svg", "Sou8.svg", "Sou9.svg", "(索)"] },
        { category: "龍類", fan: 30, name: "混一色", condition: "一門花色加番子。", example: ["Man1.svg", "-", "Man9.svg", " + ", "Ton.svg", "Ton.svg"] },
        { category: "龍類", fan: 80, name: "清一色", condition: "只有一門牌。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Man2.svg", "Man3.svg", "Man4.svg", " ", "Man5.svg", "Man6.svg", "Man7.svg", " ", "Man8.svg", "Man9.svg", "Man9.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg"] },
        { category: "龍類", fan: 30, name: "對對胡", condition: "全副刻子。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Sou1.svg", "Sou1.svg", "Sou1.svg", " ", "Pin1.svg", "Pin1.svg", "Pin1.svg", " ", "Ton.svg", "Ton.svg", "Ton.svg", " ", "Chun.svg", "Chun.svg"] },
        { category: "龍類", fan: 15, name: "全求人", condition: "全落地他人出銃。", example: ["Chun.svg", " (單一隻手牌)"] },
        { category: "極品類", fan: 80, name: "十三幺", condition: "十三么，另三隻是自己摸回來的順子或暗刻，不能上或碰回來。", example: ["Ton.svg", "Nan.svg", "Shaa.svg", "Pei.svg", "Chun.svg", "Hatsu.svg", "Haku.svg", "Man1.svg", "Man9.svg", "Sou1.svg", "Sou9.svg", "Pin1.svg", "Pin9.svg", " + ", "Man1.svg", "Man2.svg", "Man3.svg", " 或 ", "Pin3.svg", "Pin3.svg", "Pin3.svg"] },
        { category: "龍類", fan: 40, name: "十六不搭", condition: "東南西北中發白，其他三門每樣三隻，但不能搭上，例如一、四、九或二、五、九，再加一對眼。", example: ["Ton.svg", "Nan.svg", "Shaa.svg", "Pei.svg", "Chun.svg", "Hatsu.svg", "Haku.svg", " + ", "Man1.svg", "Man4.svg", "Man9.svg", " + ", "Sou1.svg", "Sou4.svg", "Sou9.svg", " + ", "Pin1.svg", "Pin4.svg", "Pin9.svg", " + ", "Hatsu.svg"] },

        { category: "門類", fan: 5, name: "缺一門", condition: "成副牌無番子，而缺少筒、索、萬其中一門", example: ["Man1.svg", "Man2.svg", "Man3.svg", " ", "Pin4.svg", "Pin5.svg", "Pin6.svg", " ", "Man7.svg", "Man8.svg", "Man9.svg", " ", "Pin1.svg", "Pin2.svg", "Pin3.svg", " ", "Pin7.svg", "Pin8.svg", "Pin9.svg", " ", "Man5.svg", "Man5.svg"] },
        { category: "門類", fan: 10, name: "五門齊", condition: "東南西北為一門，中發白為一門，筒索萬各三門。成副牌有齊五門", example: ["Ton.svg", "Ton.svg", "Ton.svg", " ", "Hatsu.svg", "Hatsu.svg", "Hatsu.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg", " ", "Sou4.svg", "Sou5.svg", "Sou6.svg", " ", "Pin7.svg", "Pin8.svg", "Pin9.svg", " ", "Sou8.svg", "Sou8.svg"] },
        { category: "門類", fan: 15, name: "七門齊", condition: "東南西北為一門，中發白為一門，筒索萬各三門，兩門花，成副牌七門都有齊", example: ["Ton.svg", "Ton.svg", "Ton.svg", " ", "Hatsu.svg", "Hatsu.svg", "Hatsu.svg", " ", "Man1.svg", "Man2.svg", "Man3.svg", " ", "Sou4.svg", "Sou5.svg", "Sou6.svg", " ", "Pin7.svg", "Pin8.svg", "Pin9.svg", " ", "Sou8.svg", "Sou8.svg", " + ", "🔹🌸"] },

        { category: "特殊大牌", fan: 40, name: "大三元", condition: "中發白三組刻子。", example: ["Chun.svg", "Chun.svg", "Chun.svg", " ", "Hatsu.svg", "Hatsu.svg", "Hatsu.svg", " ", "Haku.svg", "Haku.svg", "Haku.svg"] },
        { category: "特殊大牌", fan: 20, name: "小三元", condition: "中發白兩組刻子一對眼。", example: ["Chun.svg", "Chun.svg", "Chun.svg", " ", "Hatsu.svg", "Hatsu.svg", "Hatsu.svg", " ", "Haku.svg", "Haku.svg"] },
        { category: "特殊大牌", fan: 80, name: "大四喜", condition: "東南西北四組刻子。", example: ["Ton.svg", "Ton.svg", "Ton.svg", " ", "Nan.svg", "Nan.svg", "Nan.svg", " ", "Shaa.svg", "Shaa.svg", "Shaa.svg", " ", "Pei.svg", "Pei.svg", "Pei.svg"] },
        { category: "特殊大牌", fan: 60, name: "小四喜", condition: "風牌三組刻子一對眼。", example: ["Ton.svg", "Ton.svg", "Ton.svg", " ", "Nan.svg", "Nan.svg", "Nan.svg", " ", "Shaa.svg", "Shaa.svg", "Shaa.svg", " ", "Pei.svg", "Pei.svg"] },
        { category: "特殊大牌", fan: 30, name: "大三風", condition: "風牌三組刻子。", example: ["Ton.svg", "Ton.svg", "Ton.svg", " ", "Nan.svg", "Nan.svg", "Nan.svg", " ", "Shaa.svg", "Shaa.svg", "Shaa.svg"] },
        { category: "特殊大牌", fan: 15, name: "小三風", condition: "風牌兩組刻子一對眼。", example: ["Ton.svg", "Ton.svg", "Ton.svg", " ", "Nan.svg", "Nan.svg", "Nan.svg", " ", "Shaa.svg", "Shaa.svg"] },
        { category: "特殊大牌", fan: 80, name: "五暗刻", condition: "五個刻子在自己手裡。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " ", "Pin4.svg", "Pin4.svg", "Pin4.svg", " ", "Man6.svg", "Man6.svg", "Man6.svg", " ", "Sou8.svg", "Sou8.svg", "Sou8.svg", " ", "Ton.svg", "Ton.svg", "Ton.svg", " ", "Pin2.svg", "Pin2.svg"] },
        { category: "特殊大牌", fan: 100, name: "間間胡", condition: "自摸門前對對糊。", example: ["Man1.svg", "Man1.svg", "Man1.svg", "..."] },
        { category: "特殊大牌", fan: 40, name: "嚦咕嚦咕", condition: "八對子，三隻一樣的不能碰出。", example: ["Man1.svg", "Man1.svg", " ", "Man2.svg", "Man2.svg", " ", "Sou1.svg", "Sou1.svg", " ", "Sou2.svg", "Sou2.svg", " ", "Pin1.svg", "Pin1.svg", " ", "Pin2.svg", "Pin2.svg", " ", "Ton.svg", "Ton.svg", " ", "Chun.svg", "Chun.svg", " ", "Chun.svg"] },
        { category: "特殊大牌", fan: 10, name: "一台花", condition: "四隻同系列的花。", example: ["春夏秋冬"] },
        { category: "特殊大牌", fan: 30, name: "花胡", condition: "兩台花立刻食胡。", example: ["八花齊集"] },

        { category: "極速爆棚", fan: 100, name: "天胡", condition: "莊家起手補花後即胡。", example: ["⚡ 天選"] },
        { category: "極速爆棚", fan: 80, name: "地胡", condition: "閒家第一次摸牌即自摸。", example: ["⚡ 地靈"] },
        { category: "極速爆棚", fan: 80, name: "人胡", condition: "閒家在四隻牌內出銃食胡。", example: ["⚡ 人傑"] },
        { category: "極速爆棚", fan: 20, name: "七隻內", condition: "地下七隻牌內食胡。", example: ["⏱️ 快攻"] },
        { category: "極速爆棚", fan: 10, name: "十隻內", condition: "地下十隻牌內食胡。", example: ["⏱️ 速度"] },

        { category: "槓牌類", fan: 1, name: "明摃", condition: "碰出第四張。", example: ["Man1.svg", "Man1.svg", "Man1.svg", " + ", "Man1.svg"] },
        { category: "槓牌類", fan: 2, name: "暗摃", condition: "摸到四張相同牌。", example: ["Man1.svg", "Man1.svg", "Man1.svg", "Man1.svg"] },
        { category: "槓牌類", fan: 1, name: "花上食胡", condition: "摸花時自摸。", example: ["🌸 🖐️"] },
        { category: "槓牌類", fan: 1, name: "摃上食胡", condition: "開摃時自摸。", example: ["🎰 🖐️"] },
        { category: "槓牌類", fan: 1, name: "搶摃食胡", condition: "搶他人明槓牌。", example: ["🗡️ 摃"] },
        { category: "槓牌類", fan: 30, name: "摃上摃食胡", condition: "連續兩次開槓後自摸。", example: ["🎰🎰 🖐️"] }
    ],
    instantPay: [
        { name: "追", amount: "1底", desc: "四家打同一隻牌。" },
        { name: "暗摃", amount: "1底", desc: "需打開讓家知。" },
        { name: "一台草", amount: "0.5底", desc: "其他三家每人半底。" },
        { name: "一台花", amount: "1底", desc: "其他三家每人一底。" },
        { name: "詐胡", amount: "30番x3", desc: "罰全家。" }
    ]
};
